#!/bin/bash
echo "Running pret"

if [ "$JAVA_OPTS"  == "" ]; then
    JAVA_OPTS='-XX:+UseG1GC -XX:MaxGCPauseMillis=50'
fi

java -server -Xss4m -cp pret.jar $JAVA_OPTS clojure.main -m org.candelbio.pret.cli $*
