#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Must provide two positional arguments:"
    echo "1. database backup URI to restore from"
    echo "2. database name under which it will be restored into the local Unify system."
    exit 1
fi

util/helpers/ensure-datomic
pushd .datomic/datomic-pro-*
bin/datomic -Xmx4g -Xms4g restore-db $1 "datomic:sql://$2?jdbc:postgresql://localhost:5432/unify?user=unify&password=unify"

