#!/bin/bash
# VERSION=$(./util/version)
# echo "{:unify/version \"$VERSION\"}" > ./resources/info.edn

clojure -J-Xmx2g -J-XX:+UseG1GC -J-XX:MaxGCPauseMillis=50 -J-server -J-Xss4m -J-Dclojure.core.async.go-checking="true" -Xtest "{:includes [:integration]}"
